version: '3.3'
services:

  poke-shakespeare:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
